### ISSUE TITLE
TypeError: KafkaInputConfig.__new__() got an unexpected keyword argument 'sasl.username'

### ISSUE THREAD

**Issue by ShahNewazKhan** [bytewax/bytewax#132]
### Bug Description

Trying to use the SASL config with `KafkaInputConfig` on `Bytewax 0.11.1` that was introduced in https://github.com/bytewax/bytewax/pull/119, however recieving an input validation error:

```
TypeError: KafkaInputConfig.__new__() got an unexpected keyword argument 'sasl.username'
```

### Python version (`python -V`)

3.9.7

### Bytewax version (pip list | grep bytewax)

0.11.1

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/shahnewazkhan/projects/dapper/data-platform/wranglers/stream_processors/auth0_logs/bytewax/sasl.py", line 24, in <module>
    KafkaInputConfig(
TypeError: KafkaInputConfig.__new__() got an unexpected keyword argument 'sasl.username'
```
```


### Steps to Reproduce

from bytewax.dataflow import Dataflow
from bytewax.inputs import KafkaInputConfig
from bytewax.execution import run_main
from bytewax.outputs import StdOutputConfig
import os
import logging

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

additional_configs = {
        "sasl.username":os.environ['kafkaReaderUsername'],
        "sasl.password":os.environ['kafkaReaderPassword'],
        "sasl.mechanisms":"PLAIN",
        "security.protocol":"SASL_SSL"
    }

flow = Dataflow()
flow.input(
    "inp",
    KafkaInputConfig(
        brokers=[f"{os.environ['kafkaURL']}"],
        topic=f"{os.environ['topic']}",
        starting_offset="beginning",
        tail=False,
        **additional_configs,
    ),
)

def deserialize(key_bytes__payload_bytes):
    key_bytes, payload_bytes = key_bytes__payload_bytes
    logger.info(f'TYPE OF BYTES {type(key_bytes)}')
    return key_bytes__payload_bytes


flow.map(deserialize)

flow.capture(StdOutputConfig())

run_main(flow)

**Comment by awmatheson** [comment]
https://github.com/bytewax/bytewax/pull/119 ended up going in the direction of using `additional_properties` as an argument that expects a dictionary instead of using the keyword argument for the reason quoted below. The changes were made in #118, which made it a bit confusing since you were previously using the #119 branch.

> I think I'd rather have an argument that expects a dictionary instead of using kwargs here, since you can't actually pass a kwarg like:
> `KafkaInputConfig(sasl.username="username")`
> `# nor`
> `KafkaInputConfig("sasl.username"="username")`
> unless you put it in a dictionary and unpack it with **

You can reference the docs [here](https://docs.bytewax.io/apidocs/bytewax.inputs#bytewax.inputs.KafkaInputConfig) for a bit more information.

**Comment by ShahNewazKhan** [comment]
> #119 ended up going in the direction of using `additional_properties` as an argument that expects a dictionary instead of using the keyword argument for the reason quoted below. The changes were made in #118, which made it a bit confusing since you were previously using the #119 branch.
> 
> > I think I'd rather have an argument that expects a dictionary instead of using kwargs here, since you can't actually pass a kwarg like:
> > `KafkaInputConfig(sasl.username="username")`
> > `# nor`
> > `KafkaInputConfig("sasl.username"="username")`
> > unless you put it in a dictionary and unpack it with **
> 
> You can reference the docs [here](https://docs.bytewax.io/apidocs/bytewax.inputs#bytewax.inputs.KafkaInputConfig) for a bit more information.

That makes sense, updated accordingly and it worked, however ran into this subsequently, running :

```
...

additional_configs = {
        "sasl.username":os.environ['kafkaReaderUsername'],
        "sasl.password":os.environ['kafkaReaderPassword'],
        "sasl.mechanisms":"PLAIN",
        "security.protocol":"SASL_SSL"
    }

flow = Dataflow()
flow.input(
    "inp",
    KafkaInputConfig(
        brokers=[f"{os.environ['kafkaURL']}"],
        topic=f"{os.environ['topic']}",
        starting_offset="beginning",
        tail=False,
        additional_properties=additional_configs
    ),
)
...
```
yeilds: 

```
thread '<unnamed>' panicked at 'Error building input Kafka consumer: KafkaError (Client config error: Unsupported value "SASL_SSL" for configuration property "security.protocol": OpenSSL not available at build time security.protocol SASL_SSL)', src/inputs/kafka_input.rs:238:14
```

This was [solved](https://github.com/bytewax/bytewax/pull/119#issuecomment-1235191761) by packaging `gssapi` with Bytewax.

**Comment by whoahbot** [comment]
:wave: We've just released https://github.com/bytewax/bytewax/releases/tag/v0.11.2 which should now include `gssapi` and `ssl`.
